Postgres configuration
janus-organization/janus-real-estate pull request #1
Opened 2023-05-26 18:07 UTC by katarzynajanus

2023-05-26 18:23 UTC, MJanus2 requested changes
Please squash all commits and add with one meaningfull commit. 
Please remove .gradle/.idea and build folder from the PR. It can be created during gradle build so it is no needed to be in the repository.

2023-05-26 18:23 UTC, MJanus2 commented on build.gradle
>  	compileOnly 'org.projectlombok:lombok'
Please keep the same convention as it is in `'org.springframework.boot:spring-boot-starter-web'` in this case it should be `'org.junit:junit5-engine'`

2023-05-26 18:23 UTC, MJanus2 commented on build.gradle
>  }
Please create ext {
mockitoVersion = '2.1.0'
} 
and then implement it here as org.mockito:mockito-core:$mockitoVersion
same for JUnit5

2023-05-26 18:23 UTC, MJanus2 commented on src/main/resources/application.properties
> +spring.datasource.url=jdbc:postgresql://localhost:5432/realestate
Please convert it to yaml file. 
How to do it I found comment in the GitHub:
_for intellij-IDEA : go to file > settings > plugins then search for a plugin called: Properties to YAML Converter. Install it and After that restart your IDE then right click the application.properties file and you will get an option called "convert to yaml"_

Why:
https://www.baeldung.com/spring-boot-yaml-vs-properties

2023-06-03 12:55 UTC, katarzynajanus commented on build.gradle
>  	compileOnly 'org.projectlombok:lombok'
updated as testImplementation 'org.mockito:mockito-core:5.3.1' and 	implementation 'org.junit:junit5-engine:5.0.0-ALPHA' as I got compile error

2023-06-05 10:17 UTC, MJanus2 approved these changes

2023-06-05 10:17 UTC, merged